# Generated by Django 3.2.12 on 2022-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220309_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('korean', 'Korean')], max_length=10, null=True),
        ),
    ]
